server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Nginx logic for SPA routing (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional optimizations
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        expires max;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}
