"""capture_missing_fields_batch

Revision ID: 34e929bcf5c2
Revises: d6ad9a719af5
Create Date: 2026-03-16 16:15:11.577589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e929bcf5c2'
down_revision = 'd6ad9a719af5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.alter_column('moderation_status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('moderation_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_refresh_token'), ['refresh_token'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_refresh_token'))

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.alter_column('moderation_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('moderation_status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'pending'"))

    # ### end Alembic commands ###
