"""initial_schema

Revision ID: 8d06111fee21
Revises: 
Create Date: 2026-03-07 14:47:44.849274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d06111fee21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('page_views_portfolio_id_fkey', 'page_views', type_='foreignkey')
    op.create_foreign_key(None, 'page_views', 'portfolios', ['portfolio_id'], ['id'])
    op.alter_column('portfolios', 'template_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'standard'::character varying"))
    op.alter_column('portfolios', 'mode',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'light'::character varying"))
    op.alter_column('portfolios', 'hidden_sections',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # Check if index exists before creating
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = inspector.get_indexes('portfolios')
    index_names = [idx['name'] for idx in indexes]
    
    if 'ix_portfolios_custom_domain' not in index_names:
        op.create_index(op.f('ix_portfolios_custom_domain'), 'portfolios', ['custom_domain'], unique=True)
        
    op.drop_constraint('portfolios_user_id_fkey', 'portfolios', type_='foreignkey')
    op.create_foreign_key(None, 'portfolios', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.create_foreign_key('portfolios_user_id_fkey', 'portfolios', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_portfolios_custom_domain'), table_name='portfolios')
    op.alter_column('portfolios', 'hidden_sections',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('portfolios', 'mode',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'light'::character varying"))
    op.alter_column('portfolios', 'template_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'standard'::character varying"))
    op.drop_constraint(None, 'page_views', type_='foreignkey')
    op.create_foreign_key('page_views_portfolio_id_fkey', 'page_views', 'portfolios', ['portfolio_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
